### PR TITLE
Accepts redux-thunk and includes reducer tests

### PR DESCRIPTION
**Pull request by esganzerla**
Hi,

First of all, sorry for the big commit, if you disagree with something I did we can work it around.

In this pull request I've made:

- Accept functions that use the redux-thunk;
- Updates the README.md using a table for arguments and, obviously, how to do the tests with redux-thunk;
- Included tests for the reducerTest;
- Removed Immutable.JS since all the tests I've made worked fine without it and when there are erros return the object rather than true/false.

Thanks for these tests, it helped a lot! =)

### CODE REVIEW

**Comment by axe312ger** [comment]
Hmm test's are still failing and in my opinion, a PR should only contain one big change. Your's is massive, removing immutable completely ist IMHO not a smart idea, had some problems with it, but actually that showed me pretty well that I wrote my reducers the wrong way.

Maybe a option to turn it on/off would be great, but removing a feature from a testsuite? Nah sorry, don't think thats smart.

For the thunk thing, I don't know, I don't use `redux-thunk`, I prefer to handle side-effects via `redux-saga` and with that one, `redux-ava` works already pretty well in this version. But since a lot of people still go with `redux-thunk`, may be smart to support it :)

just my 2 cents

**Comment by esganzerla** [comment]
Hi @axe312ger

Do you mean tests are failing on Travis CI? I've checked and it is actually throwing and error when I'm declaring a default variable as a param for the function. I'm pretty sure it's the node version, I believe we should update that, right?

About the Immutable, I didn't understand very well, did you have problems with it now? I tried going deep with the results and still worked ok. Of course I can set it up again, just didn't seem like something that needed to be there, but out of curiosity, can you show me how it got problems?

I guess I really should do smaller PRs and I will.

And yeah, most projects I've seen use `redux-thunk`, including mines, so guess that's really the good part about the commit.

Thanks for the feedback

**Comment by zcei** [comment]
When I filed my first PR here it conflicted as well with the version. Node 4 should be supported though, at least until 2017-04-01, as it's a [currently active LTS](https://github.com/nodejs/LTS/)

**Comment by esganzerla** [comment]
I just broke it down in two different commits, and kept the Immutable.js now. Also fixed it for node 4.

**Pull request closed without merging**
