### PR TITLE
add tests for export and actionTest

### LINKED ISSUE #1: Write tests

### PR DESCRIPTION
**Pull request by zcei**
Hej,

as you wanted help for writing tests as well, I thought I just add them.

This is the set I would test against - currently a few fail.
Those will be green with my next PR 😏 

Closes #1

### CODE REVIEW

**Comment by sotojuan** [comment]
Cool stuff! Just a nitpick (aside from the failing tests):

* remove the new npm tasks and just make `test` be `standard | snazzy --verbose && ava --verbose`.

Aside from that it looks good to merge.

**Comment by zcei** [comment]
I thought it might make sense for a more test-driven development to have it split up.
I run the `unit-test` command way more often to test small changes, before I finally check `standard` validity (as I have it integrated in Atom either way there's hardly any output)

If you insist, I can merge the command of course 🙂

**Comment by sotojuan** [comment]
Yeah let's keep it simple for now, no big deal :-)

**Comment by zcei** [comment]
Any news on this?

**Comment by sotojuan** [comment]
Hey Stephan, sorry been away from JavaScript stuff while busy at [Recurse](http://recurse.com/). As I said this looks fine but the tests/Travis aren't passing. As soon as they do I can merge.

**Comment by sotojuan** [comment]
The [log](https://travis-ci.org/sotojuan/redux-ava/jobs/168860944) might help you figure out what's wrong.

**Comment by zcei** [comment]
Actually I noted that inside the OP, that it already includes tests for the second open PR from myself.

When I move the tests there, it will be comparing against the master and do not find any test implementation, so expect to have a weird diff in #11 until this PR is merged

**Comment by sotojuan** [comment]
Thanks!

**Pull request merged**
